### ISSUE TITLE
Azure-Sample repository missing

### ISSUE THREAD

**Issue by rallets** [hannesne/projectnewcastle#89]
Hi, I'm wondering if this repo is still up to date, because the official one [Azure-Samples | project-newcastle](https://github.com/Azure-Samples/project-newcastle/tree/master/) is not available anymore.
Any hints? 
PS. I was looking for a template for Azure Functions and typescript and this looked very interesting
Thanks for sharing

**Comment by hannesne** [comment]
Hi @rallets This sample has been moved to https://github.com/mspnp/vnet-integrated-serverless-microservices with an accompanying article in the azure architecture center.
